project_name='test1'
filterfile='Filters/Gaia/GAIA0.G.dat'
filestar='Examples/Teststar1.txt'
Columndensities='sph'
filecloud= 'Examples/NoCloud'
OBtreatment='yes'
EXTmodel='Dmodel'
Rv=3.1
alphai=0.0
bettai=0.0
gammai=0.0
res=0.05
fovx=20.
fovy=20.
distance=500.
fwhm=0.11
SNR=2.0
spectroscopy = 'yes'     # Spectroscopy output, choose 'yes' or 'no'
lminspec     = 5000.    # Minimum wavelength [A] should be set within your filter transparency
lmaxspec     = 6000.    # Maximum wavelength [A] 
Rspec        = 100 #700      # Spectral resolution (please check your SED library, should not be larger than the resolution of the SEDs)
velocitydis  = 'no'
PSFtype='gaussian'
Adaptiveoptics='no'
seeing=0.8
SR=0.8
